# Generated by Django 4.2.5 on 2023-10-01 16:28

import django.core.validators
from django.db import migrations, models
import user.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="用户名仅支持字母、数字、_、-，长度为2-16位",
                                regex="^[a-zA-Z0-9_-]{2,16}$",
                            )
                        ],
                        verbose_name="用户名",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="密码"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="手机号格式错误", regex="^1[3-9]\\d{9}$"
                            )
                        ],
                        verbose_name="手机号",
                    ),
                ),
                (
                    "avatar",
                    models.FileField(
                        default="user/avatar/default.jpg",
                        upload_to="user/avatar",
                        verbose_name="头像",
                    ),
                ),
                ("last_login", models.DateTimeField(verbose_name="最后登录时间")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "pp_user",
                "ordering": ["-create_time"],
            },
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
