"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import grpc
import grpc.aio
import paperpilot_common.protobuf.translation.translation_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class TranslationPublicServiceStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    translate: grpc.UnaryUnaryMultiCallable[
        paperpilot_common.protobuf.translation.translation_pb2.TranslationRequest,
        paperpilot_common.protobuf.translation.translation_pb2.TranslationResponse,
    ]
    """翻译"""

class TranslationPublicServiceAsyncStub:
    translate: grpc.aio.UnaryUnaryMultiCallable[
        paperpilot_common.protobuf.translation.translation_pb2.TranslationRequest,
        paperpilot_common.protobuf.translation.translation_pb2.TranslationResponse,
    ]
    """翻译"""

class TranslationPublicServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def translate(
        self,
        request: paperpilot_common.protobuf.translation.translation_pb2.TranslationRequest,
        context: _ServicerContext,
    ) -> typing.Union[
        paperpilot_common.protobuf.translation.translation_pb2.TranslationResponse,
        collections.abc.Awaitable[paperpilot_common.protobuf.translation.translation_pb2.TranslationResponse],
    ]:
        """翻译"""

def add_TranslationPublicServiceServicer_to_server(
    servicer: TranslationPublicServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]
) -> None: ...
