# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paperpilot_common/protobuf/user/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n*paperpilot_common/protobuf/user/user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t"=\n\rUserShortInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x03 \x01(\t"\xa7\x01\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"T\n\x11\x43reateUserRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t"5\n\x17UpdateUserAvatarRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x02 \x01(\t"~\n\x15UpdateUserInfoRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x14\n\x0cold_password\x18\x03 \x01(\t\x12\x14\n\x0cnew_password\x18\x04 \x01(\t\x12\r\n\x05phone\x18\x05 \x01(\t\x12\x0c\n\x04\x63ode\x18\x06 \x01(\t2\xad\x01\n\x04User\x12\x35\n\x10GetUserShortInfo\x12\x0c.user.UserId\x1a\x13.user.UserShortInfo\x12+\n\x0bGetUserInfo\x12\x0c.user.UserId\x1a\x0e.user.UserInfo\x12\x41\n\x10UpdateUserAvatar\x12\x1d.user.UpdateUserAvatarRequest\x1a\x0e.user.UserInfo2\xc0\x01\n\nUserPublic\x12\x35\n\x10GetUserShortInfo\x12\x0c.user.UserId\x1a\x13.user.UserShortInfo\x12<\n\x12GetCurrentUserInfo\x12\x16.google.protobuf.Empty\x1a\x0e.user.UserInfo\x12=\n\x0eUpdateUserInfo\x12\x1b.user.UpdateUserInfoRequest\x1a\x0e.user.UserInfob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "paperpilot_common.protobuf.user.user_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_USERID"]._serialized_start = 114
    _globals["_USERID"]._serialized_end = 134
    _globals["_USERSHORTINFO"]._serialized_start = 136
    _globals["_USERSHORTINFO"]._serialized_end = 197
    _globals["_USERINFO"]._serialized_start = 200
    _globals["_USERINFO"]._serialized_end = 367
    _globals["_CREATEUSERREQUEST"]._serialized_start = 369
    _globals["_CREATEUSERREQUEST"]._serialized_end = 453
    _globals["_UPDATEUSERAVATARREQUEST"]._serialized_start = 455
    _globals["_UPDATEUSERAVATARREQUEST"]._serialized_end = 508
    _globals["_UPDATEUSERINFOREQUEST"]._serialized_start = 510
    _globals["_UPDATEUSERINFOREQUEST"]._serialized_end = 636
    _globals["_USER"]._serialized_start = 639
    _globals["_USER"]._serialized_end = 812
    _globals["_USERPUBLIC"]._serialized_start = 815
    _globals["_USERPUBLIC"]._serialized_end = 1007
# @@protoc_insertion_point(module_scope)
