"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class UserId(google.protobuf.message.Message):
    """用户 ID"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.str
    """用户 UUID"""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___UserId = UserId

@typing_extensions.final
class UserShortInfo(google.protobuf.message.Message):
    """用户简要信息 用于展示"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    id: builtins.str
    """用户 UUID"""
    username: builtins.str
    """用户名"""
    avatar: builtins.str
    """头像"""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
        avatar: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["avatar", b"avatar", "id", b"id", "username", b"username"]
    ) -> None: ...

global___UserShortInfo = UserShortInfo

@typing_extensions.final
class UserInfo(google.protobuf.message.Message):
    """用户详细信息"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    PHONE_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    id: builtins.str
    """用户 UUID"""
    username: builtins.str
    """用户名"""
    phone: builtins.str
    """手机号"""
    avatar: builtins.str
    """头像"""
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """创建时间"""
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """更新时间"""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
        phone: builtins.str = ...,
        avatar: builtins.str = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["created_at", b"created_at", "updated_at", b"updated_at"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "avatar",
            b"avatar",
            "created_at",
            b"created_at",
            "id",
            b"id",
            "phone",
            b"phone",
            "updated_at",
            b"updated_at",
            "username",
            b"username",
        ],
    ) -> None: ...

global___UserInfo = UserInfo

@typing_extensions.final
class CreateUserRequest(google.protobuf.message.Message):
    """创建用户请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PHONE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    phone: builtins.str
    """手机号"""
    code: builtins.str
    """验证码"""
    username: builtins.str
    """用户名"""
    password: builtins.str
    """密码"""
    def __init__(
        self,
        *,
        phone: builtins.str = ...,
        code: builtins.str = ...,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "code", b"code", "password", b"password", "phone", b"phone", "username", b"username"
        ],
    ) -> None: ...

global___CreateUserRequest = CreateUserRequest

@typing_extensions.final
class UpdateUserAvatarRequest(google.protobuf.message.Message):
    """更新用户头像请求"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    id: builtins.str
    """用户 UUID"""
    avatar: builtins.str
    """头像"""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        avatar: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["avatar", b"avatar", "id", b"id"]) -> None: ...

global___UpdateUserAvatarRequest = UpdateUserAvatarRequest

@typing_extensions.final
class UpdateUserInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    OLD_PASSWORD_FIELD_NUMBER: builtins.int
    NEW_PASSWORD_FIELD_NUMBER: builtins.int
    PHONE_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    id: builtins.str
    """用户 UUID"""
    username: builtins.str
    """用户名"""
    old_password: builtins.str
    """旧密码"""
    new_password: builtins.str
    """新密码"""
    phone: builtins.str
    """手机号"""
    code: builtins.str
    """验证码"""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
        old_password: builtins.str = ...,
        new_password: builtins.str = ...,
        phone: builtins.str = ...,
        code: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "code",
            b"code",
            "id",
            b"id",
            "new_password",
            b"new_password",
            "old_password",
            b"old_password",
            "phone",
            b"phone",
            "username",
            b"username",
        ],
    ) -> None: ...

global___UpdateUserInfoRequest = UpdateUserInfoRequest
