# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from paperpilot_common.protobuf.translation import (
    translation_pb2 as paperpilot__common_dot_protobuf_dot_translation_dot_translation__pb2,
)


class TranslationPublicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.translate = channel.unary_unary(
            "/translation.TranslationPublicService/translate",
            request_serializer=paperpilot__common_dot_protobuf_dot_translation_dot_translation__pb2.TranslationRequest.SerializeToString,
            response_deserializer=paperpilot__common_dot_protobuf_dot_translation_dot_translation__pb2.TranslationResponse.FromString,
        )


class TranslationPublicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def translate(self, request, context):
        """翻译"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TranslationPublicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "translate": grpc.unary_unary_rpc_method_handler(
            servicer.translate,
            request_deserializer=paperpilot__common_dot_protobuf_dot_translation_dot_translation__pb2.TranslationRequest.FromString,
            response_serializer=paperpilot__common_dot_protobuf_dot_translation_dot_translation__pb2.TranslationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("translation.TranslationPublicService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class TranslationPublicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def translate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/translation.TranslationPublicService/translate",
            paperpilot__common_dot_protobuf_dot_translation_dot_translation__pb2.TranslationRequest.SerializeToString,
            paperpilot__common_dot_protobuf_dot_translation_dot_translation__pb2.TranslationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
