version: "3.8"
name: paperpilot-project

services:
  ### server container ##########################################
  project:
    image: registry.cn-chengdu.aliyuncs.com/ziqiang_studio/paperpilot:project
    env_file: ./.env
    networks:
      - paperpilot
      - kong_kong-net
    ports:
      - "18002:8001"

### Add Network Bridge info #########################################
networks:
  paperpilot:
    external: true
  kong_kong-net:
    external: true
