version: "3.8"
name: paperpilot-paper

services:
  ### server container ##########################################
  paper:
    image: registry.cn-chengdu.aliyuncs.com/ziqiang_studio/paperpilot:paper
    env_file: ./.env
    networks:
      - paperpilot
      - kong_kong-net
    ports:
      - "18003:8001"

### Add Network Bridge info #########################################
networks:
  paperpilot:
    external: true
  kong_kong-net:
    external: true
