version: "3.8"
name: paperpilot-monitor

services:
  ### server container ##########################################
  file:
    image: registry.cn-chengdu.aliyuncs.com/ziqiang_studio/paperpilot:monitor
    env_file: ./.env
    volumes:
      - ./config.toml:/app/config.toml
    networks:
      - paperpilot
      - kong_kong-net

### Add Network Bridge info #########################################
networks:
  paperpilot:
    external: true
  kong_kong-net:
    external: true
