# Generated by Django 4.2.6 on 2023-10-21 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="项目ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="项目名称")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="项目描述"),
                ),
                (
                    "invite_code",
                    models.CharField(max_length=64, verbose_name="邀请码"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "db_table": "pp_project",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="UserProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(db_index=True, verbose_name="用户ID"),
                ),
                (
                    "is_owner",
                    models.BooleanField(default=False, verbose_name="是否为所有者"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="project.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户项目",
                "verbose_name_plural": "用户项目",
                "db_table": "pp_user_project",
                "ordering": ["-create_time"],
            },
        ),
    ]
