"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ServerStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECTS_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    @property
    def projects(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ProjectStatus]: ...
    @property
    def time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        projects: collections.abc.Iterable[global___ProjectStatus] | None = ...,
        time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["time", b"time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["projects", b"projects", "time", b"time"]) -> None: ...

global___ServerStatus = ServerStatus

@typing_extensions.final
class ProjectStatus(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_NAME_FIELD_NUMBER: builtins.int
    PROJECT_DESCRIPTION_FIELD_NUMBER: builtins.int
    TOTAL_FIELD_NUMBER: builtins.int
    HEALTHY_FIELD_NUMBER: builtins.int
    project_name: builtins.str
    project_description: builtins.str
    total: builtins.int
    healthy: builtins.int
    def __init__(
        self,
        *,
        project_name: builtins.str = ...,
        project_description: builtins.str = ...,
        total: builtins.int = ...,
        healthy: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "healthy",
            b"healthy",
            "project_description",
            b"project_description",
            "project_name",
            b"project_name",
            "total",
            b"total",
        ],
    ) -> None: ...

global___ProjectStatus = ProjectStatus
