# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paperpilot_common/protobuf/ai/cache.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n)paperpilot_common/protobuf/ai/cache.proto\x12\x02\x61i"2\n\x07Message\x12\x16\n\x04role\x18\x01 \x01(\x0e\x32\x08.ai.Role\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t"%\n\x04\x43hat\x12\x1d\n\x08messages\x18\x01 \x03(\x0b\x32\x0b.ai.Message*\x1f\n\x04Role\x12\x08\n\x04USER\x10\x00\x12\r\n\tASSISTANT\x10\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "paperpilot_common.protobuf.ai.cache_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_ROLE"]._serialized_start = 140
    _globals["_ROLE"]._serialized_end = 171
    _globals["_MESSAGE"]._serialized_start = 49
    _globals["_MESSAGE"]._serialized_end = 99
    _globals["_CHAT"]._serialized_start = 101
    _globals["_CHAT"]._serialized_end = 138
# @@protoc_insertion_point(module_scope)
