version: "3.8"
name: paperpilot-reflection

services:
  ### server container ##########################################
  test:
    image: registry.cn-chengdu.aliyuncs.com/ziqiang_studio/paperpilot:reflection
    env_file: ./.env
    networks:
      - paperpilot
      - kong_kong-net

### Add Network Bridge info #########################################
networks:
  paperpilot:
    external: true
  kong_kong-net:
    external: true
