# Generated by Django 4.2.6 on 2023-10-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="file",
            field=models.FileField(upload_to="paper", verbose_name="文件"),
        ),
        migrations.AlterField(
            model_name="paper",
            name="publication_date",
            field=models.DateField(null=True, verbose_name="发表日期"),
        ),
    ]
