# Generated by Django 4.2.6 on 2023-10-16 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="论文ID",
                    ),
                ),
                (
                    "project_id",
                    models.UUIDField(db_index=True, verbose_name="项目ID"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("abstract", models.TextField(verbose_name="摘要")),
                (
                    "keywords",
                    models.JSONField(default=list, verbose_name="关键词列表"),
                ),
                (
                    "authors",
                    models.JSONField(default=list, verbose_name="作者列表"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签列表")),
                ("publication_date", models.DateField(verbose_name="发表日期")),
                (
                    "publication",
                    models.CharField(max_length=255, verbose_name="出版方"),
                ),
                ("volume", models.CharField(max_length=255, verbose_name="卷")),
                ("issue", models.CharField(max_length=255, verbose_name="期")),
                ("pages", models.CharField(max_length=255, verbose_name="页码")),
                ("doi", models.CharField(max_length=255, verbose_name="DOI")),
                ("url", models.CharField(max_length=255, verbose_name="URL")),
                (
                    "file",
                    models.FileField(upload_to="paper/", verbose_name="文件"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "论文",
                "verbose_name_plural": "论文",
                "db_table": "pp_paper",
                "ordering": ["-create_time"],
            },
        ),
    ]
