# Generated by Django 4.2.6 on 2023-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paper", "0002_alter_paper_file_alter_paper_publication_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paper",
            name="publication_date",
        ),
        migrations.AddField(
            model_name="paper",
            name="publication_year",
            field=models.IntegerField(default=0, verbose_name="出版年份"),
        ),
    ]
