# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Code Check

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - production


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry export --with test --without dev --output requirements.txt --without-urls
          poetry run pip install -r requirements.txt
          poetry run pip install git+https://github.com/Nagico/paperpilot-common.git#subdirectory=paperpilot-common-python
      - name: Style check
        run: |
          poetry run black --check server
          poetry run flake8 server --count --statistics
          poetry run isort --check-only server
