# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build and push docker image django
        run: |
          docker login ccr.ccs.tencentyun.com --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker build -f docker/Dockerfile -t ccr.ccs.tencentyun.com/paperpilot/paperpilot-test:latest --build-arg DJANGO_ENV=development .
          docker push ccr.ccs.tencentyun.com/paperpilot/paperpilot-test:latest
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: deploy docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/docker/paperpilot/test
            docker login ccr.ccs.tencentyun.com --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
