name: Publish to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - '*'


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        pip install poetry
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      env:
        POETRY_HOME: ${{ runner.workspace }}/.poetry
        POETRY_VIRTUALENVS_IN_PROJECT: true

    - name: Build and publish
      run: |
        cd paperpilot-common-python
        poetry build
        poetry publish --build
      env:
        POETRY_HOME: ${{ runner.workspace }}/.poetry
        POETRY_VIRTUALENVS_IN_PROJECT: true
